### ISSUE TITLE
"No such file or directory" error when trying to make only slambench

### ISSUE THREAD

**Issue by yrq0208** [nikolaradulov/slambench#14]
/media/ruiqi/95477812-1449-4c3f-b238-5295310e2d40/slambench/framework/tools/dataset-tools/TUM-ROSBAG.cpp:24:10: fatal error: tf/tf.h: No such file or directory

Has anyone else experienced this before? I have installed the deps and made them accordingly, it seems everything is fine with the installation of the deps. I googled it and it seems the tf package is ROS-related? But I don't think ROS is listed as part of the deps? Is something missing here?

TIA.

**Comment by nikolaradulov** [comment]
I can't remember seeing this issue. What have you built it on? Also could you try to see if the same problem appears using 93fa32123c8878a311ecb02acd2ad8971292a4ab ? This should at least tell us if it's introduced by the latest changes or not.

**Comment by yrq0208** [comment]
Hi @nikolaradulov , using [https://github.com/nikolaradulov/slambench/commit/93fa32123c8878a311ecb02acd2ad8971292a4ab](url) did not seem to solve the problem. I think this is because [https://github.com/nikolaradulov/slambench/commit/93fa32123c8878a311ecb02acd2ad8971292a4ab](url) concerns flann while the problem I had is with ROS.

What I have done is change line 64 in [https://github.com/nikolaradulov/slambench/blob/master/framework/tools/dataset-tools/CMakeLists.txt](url) from `set(ROSPKGS_FOUND TRUE)` to `set(ROSPKGS_FOUND FALSE)`. After that, I can build the slambench framework only without errors. 

I am closing this issue for now. @mihaibujanca can you have a look at this just to see if this change would break anything?
