### ISSUE TITLE
Issues building legoloam in docker

### ISSUE THREAD

**Issue by mihaibujanca** [nikolaradulov/slambench#27]
@yuhaozhang7 
LeGO-LOAM is failing to build in docker. It seems like for some reason the slambench wrapper lib is not being linked

```
#81 41.86 /deps/legoloam/pcl/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
#81 44.65 [ 77%] Linking CXX shared library liblegoloam-original.so
#81 45.41 [ 77%] Built target legoloam-original
#81 45.43 Scanning dependencies of target legoloam-original-library
#81 45.44 [ 88%] Building CXX object CMakeFiles/legoloam-original-library.dir/deps/legoloam/wrapper/null.cpp.o
#81 45.47 [100%] Linking CXX shared library liblegoloam-original-library.so
#81 45.77 /usr/bin/ld: skipping incompatible /deps/legoloam/wrapper//libslambench-c-wrapper.a when searching for -lslambench-c-wrapper
#81 45.77 /usr/bin/ld: cannot find -lslambench-c-wrapper
#81 45.77 collect2: error: ld returned 1 exit status
#81 45.77 make[2]: *** [CMakeFiles/legoloam-original-library.dir/build.make:268: liblegoloam-original-library.so] Error 1
#81 45.77 make[1]: *** [CMakeFiles/Makefile2:81: CMakeFiles/legoloam-original-library.dir/all] Error 2
#81 45.77 make: *** [Makefile:130: all] Error 2
------
```

**Comment by mihaibujanca** [comment]
This one seems to happen with the other libraries as well

**Comment by yuhaozhang7** [comment]
> @yuhaozhang7 LeGO-LOAM is failing to build in docker. It seems like for some reason the slambench wrapper lib is not being linked
> 
> ```
> #81 41.86 /deps/legoloam/pcl/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
> #81 44.65 [ 77%] Linking CXX shared library liblegoloam-original.so
> #81 45.41 [ 77%] Built target legoloam-original
> #81 45.43 Scanning dependencies of target legoloam-original-library
> #81 45.44 [ 88%] Building CXX object CMakeFiles/legoloam-original-library.dir/deps/legoloam/wrapper/null.cpp.o
> #81 45.47 [100%] Linking CXX shared library liblegoloam-original-library.so
> #81 45.77 /usr/bin/ld: skipping incompatible /deps/legoloam/wrapper//libslambench-c-wrapper.a when searching for -lslambench-c-wrapper
> #81 45.77 /usr/bin/ld: cannot find -lslambench-c-wrapper
> #81 45.77 collect2: error: ld returned 1 exit status
> #81 45.77 make[2]: *** [CMakeFiles/legoloam-original-library.dir/build.make:268: liblegoloam-original-library.so] Error 1
> #81 45.77 make[1]: *** [CMakeFiles/Makefile2:81: CMakeFiles/legoloam-original-library.dir/all] Error 2
> #81 45.77 make: *** [Makefile:130: all] Error 2
> ------
> ```

**Comment by yuhaozhang7** [comment]
@mihaibujanca , absolutely no idea, I have tried to build it again start with very begining, and having no problem.
If docker is still so problematic on mac, then we could choose to give up cauz we already gonna run out of the space in paper.
![捕获](https://github.com/nikolaradulov/slambench/assets/115038680/bf595e42-1c05-4d8c-a5a4-f85c0d6832fe)

**Comment by yuhaozhang7** [comment]
> This one seems to happen with the other libraries as well. Seems like you're prebuilding the static library. I don't think this is going to work across different architectures.

That might be the case, haven't think about it before
