### ISSUE TITLE
Clarification of Logged Output data from SLAMBench

### ISSUE THREAD

**Issue by OvercodedStack** [nikolaradulov/slambench#38]
Hello SLAMFuse team,

As mentioned in the title of the issue, I wanted some clarification regarding some of the logged output produced by the SLAMBench variant of SLAMFuse. I could not get SLAMBench 3.0 to run on its own so I use the one provided by SLAMFuse but the logging systems remain the same as far as I understand.

As per the title I run SLAMBench by running it through a bash script, as an example, the following command: 
`slambench i $input_directory -load $library_location/libORB_SLAM3-original-library.so -o $outputFilesLocation/"ORB3_"$dataset_type"_"$output_name_path.txt -s 1`

In the textfile produced, I can see the following data outputs: 
`Frame Number,Timestamp,ATE_RMSE,OrientationError,MeanATE,MaxATE,RPE_RMSE,Duration_Frame,CPU_Memory,GPU_Memory,X,Y,Z,`

Of importance is only 5 of these outputs: 
- ATE_RMSE
- OrientationError
- MeanATE
- MaxATE
- RPE_RMSE

I was able to track down the [paper ](https://doi.org/10.1109/IROS.2012.6385773)from where ATE and RPE were first introduced into SLAMBench or derived from, specifically for ATE RMSE and RPE RMSE. However, I was unable to understand what does the Mean and Max of ATE represent as well as the Orientation Error. How are the Means and Maxes calculated? Are these calculated on a per-frame basis or from the start to the end of the image sequence? 

What does Orientation Error represent and is it a metric based from the start to the end of the image sequence or something else? I could not find on any SLAMBench paper a reference or clear definition on Orientation Error so I would like some clarification on this metric as well. 

I am running some studies and will be basing my results on these metrics so any information will be helpful. I would also be interested in knowing if there are more metrics beyond the ones I get from log-dumping SLAMBench. 

Thank you and best regards,

E.

**Comment by OvercodedStack** [comment]
Hello SLAMFuse team,

It has been a week so I am bumping this issue again. After reviewing the data on my end, I find myself very confused at what I am looking at with RPE RMSE and ATE RMSE values. Visually, I can view the paths generated using the X,Y,Z points collected at the time RMSE is calculated. However, the numbers do not align for prediction paths that approximate themselves best with GT paths. I do not understand why is this the case when RMSE is supposed to be from start to end of the image sequence. In my view from the reviewed data, ATE values correspond loosely or not at all with any determinable trend and RPE very loosely corresponds to success in my case. 

I do not understand how SLAMBench's data generation works at all, are these values based on a path that is loop-closed during the SLAM time and the XYZ values I see are of a downscaled path? How can I infer a path is right or wrong based on the logged values? Orientation error remains a mystery flip flopping between 0 and 360. 

Can anyone please clarify what or how normally would someone use SLAMBench or SLAMFuse as a benchmarking tool during analysis?

Thank you,

E.

**Comment by nikolaradulov** [comment]
All the above metrics except for OrientationError are calculated per the entire image sequence. OrientationError represents the error between the estimated aligned orientation and the ground truth orientation, calculated on a per frame basis. 

For MaxATE and MeanATE: At each frame the absolute trajectory error is calculated as the absolute difference between the estimated aligned trajectory and the ground-truth trajectory. MaxATE is the maximum ATE observed for any of the frames in the sequence, while MeanATE is the mean of the ATE observed for any of the frames in the sequence. 

ATE_ RMSE is computed for at each frame, for the entire sequence up to said frame. At each frame there is an accumulator for the Squared ATEs seen so for eg. SumSquaredATE+=CurrentFrameATE*CurrentFrameATE . ATE_RMSE is then calculated as : sqrt(SumSquaredATE/[number of frames seen so far]). 

RPE_RMSE is also for the entire sequence. It's calculated same way as ATE_RMSE, with RPEs being accumulated for each seen frame. So at any point the reported RPE_RMSE is representative of the trajectory seen so far. 

The XYZ values are decoded directly from the pose given by the algorithm, without the pose being aligned first.

**Comment by OvercodedStack** [comment]
Hi Niko,

Thank you for your reply, it helped clear up some mysteries. I also had another set of questions:

- For ORB SLAM 2/3, is it possible to obtain the post rectificaiton path XYZ and/or XYZW quaternion rotations? 
- Can I also get the quaternion rotations for the pre-rectification path per frame?

At most, I could only see OpenVIMs supporting this information but I didn't see this information on the other SLAMs. I also know the data is accessible to some degree as the GUI option for seeing the SLAM does show the post-rectified data for the path. 

Thank you for reading and have a nice day.

**Comment by nikolaradulov** [comment]
It should be possible with some slight modifications to the code have a look at ATEMetrci.cpp , which uses the aligned trajectory. The function `Value *ATEMetric::GetValue(Phase* phase)` uses both the aligned pose and the aligned rotation, you could simply add a line to print them to a file or a command file. This being a modification to the benchmark would apply to every algorithm not just orbslam.  To get the pre-alignment pose you could modify the `sb_update_outputs` function in the orbslam interface to output the pose matrix in the command line. I believe this is what is done for OpenVins. Just beware that if you wish to modify the algorithms you will need to build it without the use of docker volumes distributed with SLAMFuse.

**Comment by OvercodedStack** [comment]
Hi Niko,

Thanks for the clarifications, I've been working in the background in fixing several issues with my dataset and using this to understand if my stuff is working or not. So far what I noticed was that Mono TUM SLAM is working perfectly with my data, however, when it comes down to my EuRoC Stereo SLAM datasets, they never work correctly. I'm not sure what exactly is the difference, as if there's some newline or text format that I am forgetting when creating the ground truth but every single time I attempt to run my ground truth through SLAMBench it's almost as if I never loaded it into SLAMBench. I can perfectly track the environment using ORB with near 100% accuracy but I cannot get correct ATE or any of the metrics to run. They all seem stuck at default origin values (~0.000001) or in Orientation Error, seem to be stuck swinging wildly between 0 - 360. 

Attached is a copy of a log that normally gets outputted from Stereo SLAM, I'm not sure this was an issue you guys have ran into before:

Slambench output:
[EuRoC Output.txt](https://github.com/user-attachments/files/17733688/EuRoC.Output.txt)

Ground truth:
[data.csv](https://github.com/user-attachments/files/17733676/data.csv)

Does ORB SLAM require IMU data to work properly in locating itself through prediction? I am only exclusively using RGB tracking so it shouldn't be the case.

**Comment by OvercodedStack** [comment]
Hello,

A small update from my investigation, apparently I did not have an issue with loading my data. Instead the issue is that in the metric calculators, none of them are getting the correct time stamp for whatever reason. Basically it fails to match GT timestamp to PRED timestamp and it never moves forward. Is there anywhere I can look to understand why prediction wouldn't initialize to the same time-stamp or work correctly?
 
![image](https://github.com/user-attachments/assets/756d8fa6-a6d7-4dcc-9047-9139367993d8)

**Comment by OvercodedStack** [comment]
Hello All,

I have fixed my issue, apparently you cannot have the names and the timestamps of the images be set from 0 - N images but need to be in nanoseconds as per the timestamps used in ground truth. This was applicable to the EuRoC dataset format. Thank you all for your help so far, my project can now progress. 

Best,

E.
